### ISSUE TITLE
Public API hardening tracking issue

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#170]
This is an aggregator for general discussion of the public API rework.

- [x] Define a split between public and private API: #172 
- [x] Remove zmsg_t from public facing interfaces: #168 
- [x] Flux API: replace json_object with string: #169
- [x] reactor callback prototypes need redesign #124
- [x] implement generic flux_open() #178
- [x] API: move module interfaces out of libflux-core.so #179
- [x] API: remove deprecated functions #180
- [ ] API: improve flux handle message counter interface #183
- [x] make comms module main() prototype conform to RFC 5 #184
- [x] create asciidoc section 3 man pages for flux api #190

**Comment by garlick** [comment]
I think this tracking issue has pretty much served its purpose, closing.
