### ISSUE TITLE
export schedutil library for use by flux-sched (and others)

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2377]
### TODO

- [x] install the compiled shared library
- [x] install the headers
- [x] create a .pc file
- [x] prefix all public function typedefs with `schedutil_`
- [ ] ~~create a man page~~

### Question

Right now the public schedutil header is actually a composite of five different headers (`hello.h`, `ready.h`, `alloc.h`, `free.h`, `ops.h`).  To avoid naming conflicts, do we want to:

- merge them into a single `schedutil.h` header?
- install them into a `schedutil` directory within `$PREFIX/include` or `$PREFIX/include/core`?
- prefix them all with `schedutil_`?

Since the individual headers are relatively small, I'm leaning towards just merging them, but I can also see why you wouldn't want to lose the structure/separation.  Any thoughts?

**Comment by grondo** [comment]
Probably just fine to merge them, but also acceptable would be to install a `schedutil.h` into `$prefix/include/flux` so it can be included with `#include <flux/schedutil.h>`. As in `flux/core.h`, `schedutil.h` just has a series of `#include "schedutil/hello.h"` .. etc.
