### ISSUE TITLE
extend expiration (time limit) of running job

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4175]
The `expiration` set in _R_ is currently static, i.e. there is no way to extend the expiration of a running job.

@garlick proposed the idea of allowing updates to the expiration via the job eventlog. Interested parties (e.g. `job-exec` module and `resource` module of a child job) could watch the eventlog and update timers or their own expiration as required.

@ryanday36, what is relative priority of this feature? I don't think we've captured it before, but perhaps it falls under the general umbrella of #2799. (Though there is a practical difference between changing the duration before the job has started and the expiration after.)
```[tasklist]
### Tasks
- [ ] https://github.com/flux-framework/flux-core/issues/5471
- [ ] https://github.com/flux-framework/flux-sched/issues/1079
- [ ] mock `sched.expiration` RPC in sched-simple
```

**Comment by ryanday36** [comment]
Yeah, I think it falls under the general rubric of #2799, although priority-wise I'd put it under 'general compute' or maybe even 'nice to have eventually' on the RM Operational Team Interlock. It'll definitely need to be aware of the work on job limits too.

**Comment by garlick** [comment]
> @garlick proposed the idea of allowing updates to the expiration via the job eventlog. 

I don't actually remember what I proposed here but given that this is essentially a resource update, it seems like we might have been thinking of something like an `R-update` event similar to [jobspec-update](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_21.html#jobspec-update-event)?  This would have the advantage of recording the change for the job record, as well as going to the job manager journal so that `job-list` could update its data.

When the job is a flux instance, we'd need some way to update the resource module's "inventory" (reflected in kvs `resource.R`) and we would also need a way to inform the scheduler of the change to _R_ through the [resource acquisition protocol](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_28.html).

**Comment by grondo** [comment]
Closing. This has been fixed.
