### ISSUE TITLE
add queue support for partitioned resources

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4439]
This issue tracks the implementation of queues for partitioned resources, needed for rollout of Flux as the native resource manager on production systems.

- [x] #4386 (default queue, and  queue-specific defaults)
- [x] #4415 (queue-specific limits)
- [x] #4437
- [x] #4438
- [x] flux-framework/flux-sched#950
- [x] flux-framework/flux-sched#960
- [x] #4440
- [x] #4441
- [x] #4580
- [x] #4442
- [x] #4494
- [x] #4602

**Comment by garlick** [comment]
I was looking for an issue on partitions and came across this.  This is really about queues, and the feature appears to be complete, so let's close this.
