### ISSUE TITLE
constrain jobs based on hostnames

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4535]
This is an issue tracking the development of a feature to allow explicitly including or excluding a list of nodes by hostname in a job request.

 - [x] Add `hostlist` operator to [RFC 31](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_31.html)
 - [x] Add `hostlist` operator to librlist match implementation for testing
 - [x] flux-framework/flux-sched#942
 - [x] flux-framework/flux-sched#965

**Comment by grondo** [comment]
Oops, this was supposed to be a feature tracking branch and the flux-sched portions of this haven't been resolved, so reopening.

**Comment by grondo** [comment]
Ok, the flux-sched PR has landed so closing this again.
