### ISSUE TITLE
flux-core 0.3.0 release

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#600]
* [x] Make the list of modules loaded by default configurable (issue #508)
* [x] Implement "run levels" for instance startup and shutdown (issue #518)
* [x] Test infrastructure changes to support sharing with flux-sched
* [ ] Simplify Flux configuration semantics (issue #452)
* [x] `flux module list` reports module status, and `flux module load` returns after module completes initialization
* [x] Solve problems with content-cache flushing to backing store (issue #573)
* [ ] Misc. test improvements

**Comment by garlick** [comment]
Closing this issue in favor of just adding the 0.3.0 milestone tag to issues for now.

**Comment by grondo** [comment]
Sorry, to comment in a closed issue, but I remember one thing I did like about this is that we were slowly building the Release Notes for the milestone version. Would it be a good idea to create a non-tracking issue: "0.3.0 Release Notes" and copy this start of release notes in and add that issue to the 0.3.0 milestone? Or is that just extra work for little benefit?

**Comment by grondo** [comment]
Oops, this was already discussed in [flux-distribution #9](https://github.com/flux-framework/distribution/issues/9#issuecomment-195565372). @trws had some great ideas in there.
