### ISSUE TITLE
multi-user support

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#756]
As described in [RFC 12](https://github.com/flux-framework/rfc/blob/master/spec_12.adoc) the Flux design calls for an instance to be able to run in multi-user mode, where programs can be launched as other users, in contrast to single-user mode in which all programs are launched as the instance owner.

This issue is a tracking issue for the problems that need to be solved to make this work.

(Creation of a tracking issue was suggested in #699)

At a high-level, multi-user support should allow a Flux instance runningas a non-privileged user to support at a minimum the features listed below.

Unless otherwise noted, capabilities granted to non-instance-owners is wholly at the discretion of the instance owner. In the rest of this document, the "non-instance-owner" shall be referred to as an "external user" for brevity. Feel free to suggest an alternative.

 * External user can access a subset of information about a running Flux instance. At a minimum, for a suitable system RM instance, this information should include
    - Resource summary (resource totals, in-use, down, and available) including
      such details of these resources as would be necessary to make valid
      job requests
    - If a scheduler is loaded, queue and running job summary, details at
      discretion of scheduler implementation and instance configuration
 * External user can submit requests to run work
 * External user can edit and control (e.g. hold, cancel, modify) running or queued jobs for which they are the owner.
 * External users have access to all data about jobs run with their identity within an instance.

Additionally a Flux instance running jobs as external users must have an ability to execute work as arbitrary identities. Since Flux does not run as a privileged user, there must be support for securely and safely allowing this work. This is an active area of design called out below. In summary, a Flux instance running mullti-user work must also have the following capabilities:

 - Ability to execute work as external user on that user's behalf with system checks to ensure all such work was fully authorized by the requesting user.
 - Ability to create/modify containers, namespaces, etc in which to run external user's work.
 - Ability to monitor, signal, terminate and clean-up resources and processes associated with user work and jobs that have exited, reached time-limit, been canceled, or have aborted.

Design activities: **Estimate: 8 FTE Months**

Comms:

 - [x] Design or extend message protocols with user identity and/or capabilities
 - [x] Design interface or capability for services to "opt-in" to handling requests from non-instance owners
 - [x] Design multi-user aware connector implementation

Execution:

 - [x] Design/architect capability for unprivileged instances to execute work as arbitrary external user
 - [ ] Interface and capability for unprivileged instances to create and manipulate containers
 - [ ] Design interface, protocol, and mechanism for external user jobs to connect back to parent instance for job wireup, job data storage, etc.
 - [ ] Examine systemd and other related work to determine if they may be leveraged for any exec capabilities listed above.

Data:
 - [ ] Architecture for job and other provenance data for non-instance owners to be carried securely with suitable privacy within an instanced owned by another arbitrary user.
 
Security:

 - [ ] Research existing user identity and secrets management systems and determine if any existing solutions may be useful in Flux to ease and/or strengthen the multi-user comms and execution designs above.

High Level Design Activities:
 - [ ] Update [RFC 12](https://github.com/flux-framework/rfc/blob/master/spec_12.adoc) with full summary of revised multi-user security architecture
 - [ ] Building on design activities above, review use cases and functionality requirements for full RM capability on a single cluster, and provide a set of novel Flux services and changes to existing Flux services  which shall satisfy the requirements of minimum functional multi-user RM capability.

Development Activities: **Estimate: TBD**

**Comment by garlick** [comment]
Completed a while ago.
