### ISSUE TITLE
start flux broker from systemd

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#967]
Brokers for a system instance will be started/managed by systemd.   The architecture of the system instance is not yet designed, but we could make some progress on issues we _know_ we will need to solve by arranging for a single node instance to be started by systemd.

Here are a few of the challenges:

- [x] add systemd unit file (fixed in #995)
- [x] add "rc2" initial program (fixed in #995 - use `sleep inf` for now)
- [x] use well known path for local:// socket connector (fixed in #992)
- [x] modify `flux_open()` to to use well known socket if FLUX_URI is not set (fixed in #992)
- [ ] should job id be set to system name or similar? (fixed in #995)
- [x] should tmpdir be located in /var/run or similar? (fixed in #992)

**Comment by garlick** [comment]
In putting together a simple systemd unit file, I ran into two problems with a flux user created with `useradd --system flux` on Ubuntu.  First, the rc1 script wouldn't run until I gave "flux" a valid shell.  Second, flux keys are currently stored in the user's $HOME, and a user added in this way doesn't get one.  We'll probably want to fix the key location and I'm not sure what exactly is preventing rc1 from running since it has a valid shebang.

**Comment by garlick** [comment]
Dropping these items from tracker:

> use well known socket for overlay endpoint (or suppress for single rank)

Suppress for single rank.

> should we clear content cache etc on every startup?  should anything persist across reboot?

Content is created in `/var/run/flux` so it is cleared for now.  In addition, the content cache and kvs do not have an option to start from a previously saved state, though such would be simple to add.

> orderly shutdown of workload on receipt of SIGTERM from "stop" command

A long standing issue that's not going to get solved here, see #25

**Comment by garlick** [comment]
With #995 merged I think I'll close this.
